NumPy — это библиотека языка Python для работы с большими многомерными массивами и матрицами.
Основным объектом NumPy является однородный многомерный массив numpy.ndarray.

Наиболее важные атрибуты объектов ndarray:

ndarray.ndim - число измерений (чаще их называют "оси") массива.

ndarray.shape - размеры массива, его форма. Это кортеж натуральных чисел, показывающий длину массива по каждой оси. Для матрицы из n строк и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.

ndarray.size - количество элементов массива. Очевидно, равно произведению всех элементов атрибута shape.

ndarray.dtype - объект, описывающий тип элементов массива. Можно определить dtype, используя стандартные типы данных Python. NumPy здесь предоставляет целый букет возможностей, как встроенных, например: bool_, character, int8, int16, int32, int64, float8, float16, float32, float64, complex64, object_, так и возможность определить собственные типы данных, в том числе и составные.

ndarray.itemsize - размер каждого элемента массива в байтах.

https://physics.susu.ru/vorontsov/language/numpy.html

In [1]:
# импорт библиотеки в наш проект
import numpy as np

Создание массивов
В NumPy существует много способов создать массив. 
Один из наиболее простых - создать массив из обычных списков или кортежей Python, используя функцию numpy.array()


In [2]:
arr = np.array([1, 2, 3])
list_new = [4,5,6]
arr2 = np.array(list_new)
arr3 = np.array((6,7,8))
print('Массив1: {}'.format(arr))
print('Массив2: {}'.format(arr2))
print('Массив3: {}'.format(arr3))
print(type(arr))

Массив1: [1 2 3]
Массив2: [4 5 6]
Массив3: [6 7 8]
<class 'numpy.ndarray'>


Функция array() трансформирует вложенные последовательности в многомерные массивы. 
ВАЖНО: Тип элементов массива зависит от типа элементов исходной последовательности (но можно и переопределить его в момент создания).


In [3]:
b = np.array([[1.5, 2, 3], [4, 5, 6]])
print('Массив4:\n {}'.format(b))


Массив4:
 [[1.5 2.  3. ]
 [4.  5.  6. ]]


Можно также переопределить тип в момент создания:

In [6]:
b1 = np.array([[1.5, 2, 3], [4, 5, 6]], dtype=np.int)
b2 = np.array([[1.5, 2+3j, 3], [4, 5, 6]])
print('Массив5:\n {}'.format(b1))

print('Массив5:\n {}'.format(b2))

Массив5:
 [[1 2 3]
 [4 5 6]]
Массив5:
 [[1.5+0.j 2. +3.j 3. +0.j]
 [4. +0.j 5. +0.j 6. +0.j]]


Функция array() не единственная функция для создания массивов. 
Обычно элементы массива вначале неизвестны, а массив, в котором они будут храниться, уже нужен.
Поэтому имеется несколько функций для того, чтобы создавать массивы с каким-то исходным содержимым (по умолчанию тип создаваемого массива — float64).

Функция zeros() создает массив из нулей, 
а функция ones() — массив из единиц. 
ВАЖНО: Обе функции принимают кортеж с размерами и аргумент dtype.

In [7]:
z = np.zeros((3, 5))
o = np.ones((2, 2))

print('Массив нулевой:\n {}'.format(z))

print('Массив единичный:\n {}'.format(o))

Массив нулевой:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Массив единичный:
 [[1. 1.]
 [1. 1.]]


Функция eye() создаёт единичную матрицу (двумерный массив c единичной диагональю)
(ВАЖНО: двухмерную диагональную со сдвигом)

In [11]:
mas1 = np.eye(5,k = -2)
print('Двумерный массив единичный:\n {}'.format(mas1))

Двумерный массив единичный:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


Функция empty() создает массив без его заполнения. 
Исходное содержимое случайно и зависит от состояния памяти на момент создания массива 
(то есть от того мусора, что в ней хранится):

In [12]:
mas2 = np.empty((2, 2))
print('Абсолютно пустой массив :\n {}'.format(mas2))

Абсолютно пустой массив :
 [[1. 1.]
 [1. 1.]]


Создать единичную матрица (квадратную) можно с помощью функции identity(N[, dtype])

In [16]:
mas22 = np.identity(4,dtype = np.int)
print('Единичная квадратная матрица :\n {}'.format(mas22))

Единичная квадратная матрица :
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
#range(0,n-1,step)
for i in range(0,10):
    print(i)

Для создания последовательностей чисел, в NumPy имеется функция arange(), аналогичная встроенной в Python range(), 
только вместо списков она возвращает массивы, и принимает не только целые значения - ВАЖНО!

In [18]:
masaslist1 = np.arange(10, 30, 5)

masaslist2 = np.arange(0, 1, 0.1)

print('Список 1 :\n {}'.format(masaslist1))
print('Список 2 :\n {}'.format(masaslist2))

print(type(masaslist2))

Список 1 :
 [10 15 20 25]
Список 2 :
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
<class 'numpy.ndarray'>


При использовании arange() с аргументами типа float не всегда будешь уверенным в том, сколько элементов будет получено (из-за ограничения точности чисел с плавающей запятой).
Поэтому, в таких случаях обычно лучше использовать функцию linspace(), которая вместо шага в качестве одного из аргументов принимает число, равное количеству нужных элементов.

In [19]:

 # Список из 9 чисел от 0 до 2 включительно
list3 = np.linspace(0, 2, 9) 
print('Список из 9 чисел от 0 до 2 включительно :\n {}'.format(list3))

Список из 9 чисел от 0 до 2 включительно :
 [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


Иногда требуется применить какую-то функцию ко всем комбинациям индексов (те ко всей матрице/массиву),
например каждый элемент массива определить по какому-то выражению.
Нам поможет функция fromfunction(имя_функции , кортеж из индексов матрицы)

 кортеж из индексов матрицы - Форма выходного массива, который также определяет форму массивов координат, переданных в функцию.

In [21]:
def f1(i,j):
    x = i**2 + j**2
    return x


a = np.fromfunction(f1, (10,10),dtype = np.int)
print('Массив , прошедший через функцию:\n {}'.format(a))



Массив , прошедший через функцию:
 [[  0   1   4   9  16  25  36  49  64  81]
 [  1   2   5  10  17  26  37  50  65  82]
 [  4   5   8  13  20  29  40  53  68  85]
 [  9  10  13  18  25  34  45  58  73  90]
 [ 16  17  20  25  32  41  52  65  80  97]
 [ 25  26  29  34  41  50  61  74  89 106]
 [ 36  37  40  45  52  61  72  85 100 117]
 [ 49  50  53  58  65  74  85  98 113 130]
 [ 64  65  68  73  80  89 100 113 128 145]
 [ 81  82  85  90  97 106 117 130 145 162]]


Создать нижную треугольную матрицу (из единиц) позволяет функция tri(N[, M, k, dtype])

In [24]:
mas4 = np.tri(3, 5, k = 1, dtype=np.float)
print('Нижняя треугольная матрица:\n {}'.format(mas4))

Нижняя треугольная матрица:
 [[1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]]


Для обхода матриц любой размерности в numpy можно использовать функцию --
многомерный индексовый итератор np.ndenumerate(), 
предоставляющий пару:
набор координат (кортеж)
и значение элемента матрицы

In [25]:
a = np.array([[1, 2], [3, 4]])
for index, x in np.ndenumerate(a):
    print('index = {}-{}, x = {}'.format(index[0],index[1], x))

index = 0-0, x = 1
index = 0-1, x = 2
index = 1-0, x = 3
index = 1-1, x = 4


Задание1: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы. 
Для X =np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) (ответ 3).

In [26]:
X = np.array([[1, 0, 1, 3], [2, 0, 2, 4], [3, 0, 3, 6], [4, 4, 4, 4]])
print('Матрица:\n {}'.format(X))
mul = 1
for index, x in np.ndenumerate(X):
    print('index = {}, x = {}'.format(index, x))
    if (index[0] == index[1]) & (x > 0):
        #print(x)
        mul *= x
print('Произведение ненулевых элементов на диагонали прямоугольной матрицы = {} '.format(mul))
        

Матрица:
 [[1 0 1 3]
 [2 0 2 4]
 [3 0 3 6]
 [4 4 4 4]]
index = (0, 0), x = 1
index = (0, 1), x = 0
index = (0, 2), x = 1
index = (0, 3), x = 3
index = (1, 0), x = 2
index = (1, 1), x = 0
index = (1, 2), x = 2
index = (1, 3), x = 4
index = (2, 0), x = 3
index = (2, 1), x = 0
index = (2, 2), x = 3
index = (2, 3), x = 6
index = (3, 0), x = 4
index = (3, 1), x = 4
index = (3, 2), x = 4
index = (3, 3), x = 4
Произведение ненулевых элементов на диагонали прямоугольной матрицы = 12 


Задание 2:
Найти максимальный элемент в векторе x среди элементов, перед которыми стоит нулевой. 
Для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.


In [27]:
mas = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) 
print('Матрица:\n {}'.format(mas))

max_mas = 0
for i, x in np.ndenumerate(mas):
    #print('index = {}, x = {}'.format(i[0], x))
    if  (x == 0) & (len(mas)-1 > i[0]) :
        inew = i[0] + 1
        
        if max_mas< mas[inew]:
            max_mas = mas[inew]            
       
print('максимальный элемент в векторе x среди элементов, перед которыми стоит нулевой = {} '.format(max_mas))

Матрица:
 [6 2 0 3 0 0 5 7 0]
максимальный элемент в векторе x среди элементов, перед которыми стоит нулевой = 5 


Дополнительным преимуществом NumPy является наличие в нем функций агрегирования:
min()
max()
avg()
mean()    позволяет получить среднее арифметическое;
prod()   выдает результат умножения всех элементов;
std()    среднеквадратическое отклонение.

In [28]:
l=[1,2,38,4,-1,2,34]
mas = np.array(l)


print('Min = {}'.format(mas.min()))
print('MAx = {}'.format(mas.max()))
print('Avg = {}'.format(mas.sum()))
print('Mean = {:.4f}'.format(mas.mean()))
print('Mul = {}'.format(mas.prod()))
print('std = {:.4f}'.format(mas.std()))


Min = -1
MAx = 38
Avg = 80
Mean = 11.4286
Mul = -20672
std = 15.6375


Методы argmin() и argmax() возвращают индексы минимального и
максимального элементов по всему массиву или по строкам (столбцам). При
определении индекса по всему массиву он вначале выравнивается построчно до
одномерного массива. Затем возвращается индекс элемента в таком массиве.

In [ ]:
print('Min index = {}'.format(mas.argmin()))
print('Max index = {}'.format(mas.argmax()))

Арифметические операции над массивами NumPy:

Создадим два массива NumPy и посмотрим как можно их использовать.

Сложение: При сложении массивов складываются значения каждого ряда. Это сделать очень просто, достаточно написать data + ones:
использование абстракций подобного рода не требует написания циклов for с вычислениями. Это отличная абстракция, которая позволяет оценить поставленную задачу на более высоком уровне.

Помимо сложения, здесь также можно выполнить следующие простые арифметические операции:вычитание, умножение, деление.


In [29]:
one = np.array([2,4,5,3])
second= np.array([3,1,2,5])

sums = one + second
print('sum = {}'.format(sums))

mult = one * second
print('mult = {}'.format(mult))

subs = one - second
print('subs = {}'.format(subs))

#div = np.around(one / second,2)
div = one / second
div = np.around(div,2)

print('div = {}'.format(div))

sum = [5 5 7 8]
mult = [ 6  4 10 15]
subs = [-1  3  3 -2]
div = [0.67 4.   2.5  0.6 ]


Довольно часто требуется выполнить какую-то арифметическую операцию между массивом и простым числом: операция между вектором и скалярной величиной. 
Предположим, что в массиве указано расстояние в милях, и его нужно перевести в километры. 
Для этого нужно выполнить операцию data * 1.6:
NumPy  умножает на указанное число  каждый элемент массива. 
Данная концепт называется трансляцией, или broadcating.

In [30]:
data = [23.45, 2, 3, 44.6]

data = np.array(data)
data_km = data * 1.6

print('Растояния в милях = {}'.format(data))
print('Растояния в км = {}'.format(data_km))


Растояния в милях = [23.45  2.    3.   44.6 ]
Растояния в км = [37.52  3.2   4.8  71.36]


Индексация массива NumPy

Массив NumPy можно разделить на части, используя индексы. Принцип работы похож на то, как это происходит со списками Python.




In [31]:

data = np.array([23, 45, 2, 3, 46, 23.45, 2, 3, 44, 6])

print(data[0:3])
print(data[1:5])

print(data[3])

[23. 45.  2.]
[45.  2.  3. 46.]
3.0


In [32]:
data = np.array([[23,45, 3],[46, 23.45, 2],[3,44,6]])
print(data)

[[23.   45.    3.  ]
 [46.   23.45  2.  ]
 [ 3.   44.    6.  ]]


In [35]:
#можем вырезать части из массива  с помощью срезов

#print(data[1][2])
#print(data[1:3])

# из матрицы можно вырезать , указав срезы по  
A = np.array([[1, 4, 5, 12, 14], 
    [-5, 8, 9, 0, 17],
    [-6, 7, 11, 19, 21]])
print(A)
print(A[:2, :4])  # две строки, четыре столбца

[[ 1  4  5 12 14]
 [-5  8  9  0 17]
 [-6  7 11 19 21]]
[[ 1  4  5 12]
 [-5  8  9  0]]


К элементам массива можно применять различные функции.
Функции, определенные для массивов:
trunc(x)	отбрасывание дробной части (по элементам)
floor(x)	целая часть
ceil(x)	минимальное целое большее числа
sign(x)	знаки элементов
conj(x)	комплексное сопряжение (по элементам).
exp(x)	экспонента (по элементам)
exp2(x)	2**элемент (по элементам)
log(x)	натуральный логарифм (по элементам)
log2(x)	двоичный логарифм (по элементам)
log10(x)	десятичный логарифм (по элементам)
expm1(x)	exp(x) - 1 (по элементам)
log1p(x)	Return the natural logarithm of one plus the input array, element-wise.
    sqrt(x)	квадратный корень (для положительных) (по элементам)
square(x)	квадрат (по элементам)

x – массив
out – место для результата

In [36]:
import numpy as np
mas = np.array([1,2,3,1,2,1])

mas2 = np.around(np.log(mas),3)
mas3 = np.square(mas)

print('Массив исходный = {}'.format(mas))

print('Массив log = {}'.format(mas2))

print('Массив квадратов элементов = {}'.format(mas3))

Массив исходный = [1 2 3 1 2 1]
Массив log = [0.    0.693 1.099 0.    0.693 0.   ]
Массив квадратов элементов = [1 4 9 1 4 1]


Элементы линейной алгебры.
Функции подмодуля numpy.linalg  реализует основные
операции линейной алгебры. 
Здесь мы опишем только наиболее важные функции этих модулей. При
этом для краткости не будем упоминать о необязательных аргументах многих
функций. В тех случаях, когда они есть, но мы о них не упоминаем, в описании
будут использоваться квадратные скобки, означающие необязательность, и
троеточие, обозначающее пропуск в описании одного или нескольких
аргументов. Например, norm(a[,ord,...]) означает, что a является
обязательным аргументом, кроме того может использоваться необязательный
аргумент ord и могут быть другие необязательные аргументы. 


Функция det(a[,...]) вычисляет определитель квадратной матрицы.

Функция norm(a[,ord,...]) вычисляет норму массива (вектора или
матрицы).
Второй аргумент определяет вид нормы (Евклида, Фробениуса, Минковского и
т.д.). Если аргумент ord опущен, то вычисляется норма Евклида.


In [37]:
import numpy as np
import numpy.linalg as nplg
mas = np.array([[1,2],[3,1]])

print('Массив исходный =\n {}'.format(mas))
det_mas = nplg.det(mas)
print('Определитель матрицы =\n {:.2f}'.format(det_mas))
norm_mas = nplg.norm(mas)
print('Норма матрицы =\n {:.2f}'.format(norm_mas))

Массив исходный =
 [[1 2]
 [3 1]]
Определитель матрицы =
 -5.00
Норма матрицы =
 3.87


In [38]:
sum_kv = np.square(mas)
print(sum_kv.sum()**(1/2))

3.872983346207417


Функция inv(a[,...]) вычисляет обратную матрицу/массив.
Проверим, что a*a1=I. 


In [39]:
mas = np.array([[1,2],[3,1]])

print('Матрица исходный =\n {}'.format(mas))

mas_obr = nplg.inv(mas)

print('Матрица обратная  =\n {}'.format(mas_obr))

Матрица исходный =
 [[1 2]
 [3 1]]
Матрица обратная  =
 [[-0.2  0.4]
 [ 0.6 -0.2]]


In [41]:
mas_ones = mas * mas_obr
#print('Матрица обратная  =\n {}'.format(mas_ones))


#dot(a, b)	скалярное произведение массивов


mas_ones2 = np.dot(mas , mas_obr)

print('Матрица единичная  =\n {}'.format(mas_ones2))

Матрица единичная  =
 [[1. 0.]
 [0. 1.]]


Функция solve(a,b) решает систему линейных уравнений
A*x = b, где
A – квадратная матрица (массив) коэффициентов, 
а b – вектор (массив) правыхчастей системы.

Решение систем линейных алгебраических уравнений:
1. A* x = b - Матричная запись системы
2. убедиться, что решение есть, или их много, или не существует: найти ранг матрицы и ранг расширенной матрицы
3. найти решение одним из способов (обратная матрица, функция solve)



In [42]:
A = np.array([[1,2,1,1],[-2,2,0,0],[1,3,1,2],[4,1,1,2]])
b = np.array([-1,1,3,4])


Теперь надо убедиться, что решения либо существуют , либо нет.
Поговорим о ранге матрицы
Ранг матрицы является еще одной важной численной характеристикой матрицы. 
Рангом называют максимальное число линейно независимых строк (столбцов) матрицы. 
Линейная независимость означает, что строки (столбцы) не могут быть линейно выражены через другие строки (столбцы). 
Ранг матрицы можно найти через ее миноры, он равен наибольшему порядку минора, который не равен нулю. 
Существование ранга у матрицы не зависит от того квадратная она или нет.
np.linalg.matrix_rank() возвращает ранг матрицы.

In [43]:
rank = np.linalg.matrix_rank(A)
print(rank)

4


Чтобы найти ранг расширенной матрицы необходимо соединить матрицу А и в.

Поговорим об объединении массивов в numpy.
Несколько массивов могут быть объединены вместе вдоль разных осей с помощью функций hstack и vstack.

hstack() объединяет массивы по первым осям, 
vstack() — по последним.
Функция column_stack() объединяет одномерные массивы в качестве столбцов двумерного массива.
Аналогично для строк имеется функция row_stack().

In [44]:
print('A:\n {}'.format(A))
print('b:\n {}'.format(b))


Ab = np.column_stack((A,b))


print('Ab:\n {}'.format(Ab))


A:
 [[ 1  2  1  1]
 [-2  2  0  0]
 [ 1  3  1  2]
 [ 4  1  1  2]]
b:
 [-1  1  3  4]
Ab:
 [[ 1  2  1  1 -1]
 [-2  2  0  0  1]
 [ 1  3  1  2  3]
 [ 4  1  1  2  4]]


In [45]:
rank1= np.linalg.matrix_rank(Ab)
print(rank1)


4


если ранг и ранг расширенной матрицы равны и равны m = n, то имеется одно решение.
если ранг меньше ранга расширенной матрицы - решения нет


In [46]:
# первый способ: с помощью обратной матрицы
#Ax=B=> x = A^(-1)*b
# x = A^-1  * b
A_obr = nplg.inv(A)

#x1 = A_obr * b
x = np.dot(A_obr , b)

print('Решение системы: \n{}'.format(x))


Решение системы: 
[ 2.   2.5 -9.5  1.5]


In [47]:
#второй способ: solve


x2 = nplg.solve(A,b)
print('Решение системы: \n{}'.format(x2))

Решение системы: 
[ 2.   2.5 -9.5  1.5]


In [48]:
#Проверка 1 :

b = np.dot(A , x)
print('{}'.format(b))

[-1.  1.  3.  4.]
